In [5]:
# Question 1.Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
# question 2. Create a vector with values ranging from 10 to 49.

import numpy as np
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#Question 3. Create a 3x3 matrix with values ranging from 0 to 8.
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
#Question 4. Find indices of non-zero elements from [1,2,0,0,4,0].
arr = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(arr)
non_zero


(array([0, 1, 4], dtype=int64),)

In [18]:
#Question 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_array = np.random.rand(10,10)
min_value = random_array.min()
max_value = random_array.max()
print("Random Array:")
print(random_array)
print("Minimum Value:",min_value)
print("Maximum Value:",max_value)


Random Array:
[[6.72622530e-04 4.53250618e-01 2.59851051e-01 7.19564096e-01
  1.62943751e-02 8.45410140e-01 3.97771749e-02 4.93232834e-01
  4.92414503e-01 5.66743374e-01]
 [5.14311184e-01 8.81406503e-01 3.79696888e-01 7.53264853e-01
  3.05425618e-01 3.28619112e-01 2.03245275e-01 9.20027322e-01
  5.05538827e-01 1.53299688e-01]
 [8.62666681e-01 8.46191279e-01 5.56068813e-01 8.86419777e-01
  7.52434621e-03 3.94107021e-01 9.86876407e-01 3.67330804e-01
  7.57986672e-01 4.59336730e-01]
 [5.63328298e-01 8.47088252e-03 4.47247994e-01 4.59705567e-01
  8.07486839e-01 6.87698549e-01 8.38803157e-01 4.67683513e-01
  7.95004754e-01 3.96355311e-01]
 [8.71211481e-01 2.20578419e-02 7.71379465e-01 2.81108381e-01
  7.14121862e-01 1.77182656e-01 6.70920963e-01 9.64188799e-01
  2.96232263e-01 2.73976543e-01]
 [3.12468350e-02 2.62313900e-01 3.87328578e-01 4.62093782e-02
  2.56792862e-01 8.38578135e-02 5.84741618e-01 2.45499710e-01
  8.97730541e-01 1.85926862e-01]
 [3.37069552e-01 2.22766125e-01 3.23697733e-

In [21]:
#Question 6. Create a random vector of size 30 and find the mean value.
random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print("Random Vector:")
print(random_vector)
print("Mean Value:", mean_value)

Random Vector:
[0.35127927 0.96330462 0.74897238 0.8165068  0.95775651 0.02079497
 0.9932426  0.30319494 0.64189423 0.66687893 0.43619089 0.15540151
 0.52479246 0.33814995 0.10144286 0.76915844 0.12015259 0.79903393
 0.23065803 0.32486119 0.53559585 0.52567671 0.71674358 0.64032486
 0.22282265 0.0927448  0.5151099  0.67611111 0.08722107 0.42012633]
Mean Value: 0.4898714647271436
